# Generated by Django 4.2.1 on 2023-05-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_attendanceclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='classname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
