# Generated by Django 4.2.1 on 2023-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_class_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2023-02-16'),
        ),
    ]
