# Generated by Django 4.2.1 on 2023-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
