# Generated by Django 4.2.1 on 2023-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_course_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
